# Generated by Django 5.2.6 on 2025-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250, verbose_name='Задача')),
                ('state', models.BooleanField(default=False, verbose_name='Статус выполнения')),
            ],
        ),
    ]
